### ISSUE TITLE
Method "flickr.token.valid" not found

### ISSUE THREAD

**Issue by zdmytriv** [inspector2211/flickrsmartsync_oauth#1]
Got an error

```
$ flickrsmartsync_oauth
Traceback (most recent call last):
  File "/usr/local/bin/flickrsmartsync_oauth", line 11, in <module>
    load_entry_point('flickrsmartsync-oauth==0.1.0.post0', 'console_scripts', 'flickrsmartsync_oauth')()
  File "/usr/local/lib/python2.7/site-packages/flickrsmartsync_oauth-0.1.0.post0-py2.7.egg/flickrsmartsync_oauth/__init__.py", line 57, in main
    remote = Remote(args)
  File "/usr/local/lib/python2.7/site-packages/flickrsmartsync_oauth-0.1.0.post0-py2.7.egg/flickrsmartsync_oauth/remote.py", line 21, in __init__
    self.auth_api() # removed return token
  File "/usr/local/lib/python2.7/site-packages/flickrsmartsync_oauth-0.1.0.post0-py2.7.egg/flickrsmartsync_oauth/remote.py", line 38, in auth_api
    if not self.api.token_valid(perms=u'delete'):
  File "/usr/local/lib/python2.7/site-packages/flickrapi/__init__.py", line 357, in handler
    parse_format=args['format'], **args)
  File "/usr/local/lib/python2.7/site-packages/flickrapi/__init__.py", line 444, in __wrap_in_parser
    return parser(self, data)
  File "/usr/local/lib/python2.7/site-packages/flickrapi/__init__.py", line 285, in parse_etree
    raise FlickrError(u'Error: %(code)s: %(msg)s' % err.attrib)
flickrapi.exceptions.FlickrError: Error: 112: Method "flickr.token.valid" not found
```

**Comment by inspector2211** [comment]
@zdmytriv 

I think you are using version 1.4.4 of flickrapi (that is, the version included with flickrsmartsync).

The last three lines of your error refer to line 285 of flickrapi/__init__.py
    raise FlickrError(u'Error: %(code)s: %(msg)s' % err.attrib).

flickrsmartsync_oauth uses the latest version 2.3 of flickrapi.  In version 2.3, flickrapi/__init__.py is only 81 lines.

**Comment by zdmytriv** [comment]
```
python setup.py install
...
Installed /usr/local/lib/python2.7/site-packages/flickrsmartsync_oauth-0.1.0.post0-py2.7.egg
Processing dependencies for flickrsmartsync-oauth==0.1.0.post0
Searching for flickrapi==2.3
Best match: flickrapi 2.3
Processing flickrapi-2.3-py2.7.egg
flickrapi 2.3 is already the active version in easy-install.pth
```

[Complete output](https://gist.github.com/zdmytriv/c6553c07097a51edae6f43ca6da40ba1)

Also 

```
$ pip list | grep flickr
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
flickrapi (2.3)
flickrsmartsync (0.2.2.post0)
flickrsmartsync-oauth (0.1.0.post0)
```

**Comment by zdmytriv** [comment]
I've tried it from clean virtual env and it worked! Looks like it was problem with my local env. Thanks for your help. Closing this issue.
